openapi:
  title: backend API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.
  enable: true

drift:
  log_statements: true
postgres:
  host: localhost
  database: postgres
  port: 5432
  username: todo
  password: password
  ssl: disable
server:
  port: 8080
  host: localhost

storage:
  provider: local  # opções: local, s3, firebase
  local:
    folder: './uploads'
  s3:
    bucket: 'meu-bucket'
    region: 'us-east-1'
    accessKey: 'sua_access_key'
    secretKey: 'seu_secret_key'
  firebase:
    projectId: 'my-project'
    apiKey: 'my_api'

env:
  base_url: http://localhost
  mode: debug