name: backend
description: Todo backend.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  postgres: ^3.5.8
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.2
  dio: ^5.9.0
  drift_postgres: ^1.3.1
  drift: ^2.9.0
  vaden_security: ^1.0.0
  vaden: ^1.0.2
  domain:

dev_dependencies:
  drift_dev: ^2.29.0
  build_runner: ^2.10.3
  vaden_class_scanner: ^1.0.2